version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 8080:80
        volumes:
          # - "/home/nikolay89/bgapp/web:/var/www/html:ro"
          # We have to create .env file where we have to define verables
            - "${PROJECT_ROOT}:/var/www/html:ro"
        networks:
            - app-network
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - app-network
        environment:
          #MYSQL_ROOT_PASSWORD: "12345"
          MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:

